/**
 * Ownership Model — src/lib/ownership-model.server.ts
 *
 * يُحدّد Module Owner / Service Owner / Critical Component Owner
 * لضمان المسؤولية الواضحة في كل جزء من النظام.
 */

import { logger } from "@/lib/logger.server";

// ─── الأنواع ────────────────────────────────────────────────────────────────

export type OwnershipLevel = "primary" | "secondary" | "approver";

export interface ComponentOwner {
  userId: string;
  name: string;
  email: string;
  level: OwnershipLevel;
  since: Date;
}

export interface ComponentOwnership {
  componentId: string;
  componentType: "module" | "service" | "file" | "critical_system" | "agent" | "database_table";
  componentName: string;
  path?: string;
  owners: ComponentOwner[];
  primaryOwner: ComponentOwner;
  requiredApprovals: number;
  isCritical: boolean;
  escalationEmail?: string;
  lastReviewed?: Date;
  reviewFrequencyDays: number;
}

export interface OwnershipReport {
  totalComponents: number;
  orphanedComponents: ComponentOwnership[];
  overloadedOwners: Array<{ owner: ComponentOwner; componentCount: number }>;
  overdueReviews: ComponentOwnership[];
  criticalWithSingleOwner: ComponentOwnership[];
  summary: string;
}

// ─── OwnershipRegistry ───────────────────────────────────────────────────────

export class OwnershipRegistry {
  private ownerships: Map<string, ComponentOwnership> = new Map();

  /**
   * يُسجّل ملكية مكوّن
   */
  register(ownership: ComponentOwnership): void {
    this.ownerships.set(ownership.componentId, ownership);
    logger.info("Ownership registered", {
      componentId: ownership.componentId,
      primaryOwner: ownership.primaryOwner.email,
    });
  }

  /**
   * يُحدّث مالك مكوّن
   */
  updateOwner(componentId: string, owner: ComponentOwner): void {
    const comp = this.ownerships.get(componentId);
    if (!comp) throw new Error(`Component ${componentId} not found`);

    if (owner.level === "primary") {
      comp.primaryOwner = owner;
      const existing = comp.owners.findIndex((o) => o.level === "primary");
      if (existing >= 0) comp.owners[existing] = owner;
      else comp.owners.push(owner);
    } else {
      comp.owners.push(owner);
    }

    this.ownerships.set(componentId, comp);
  }

  /**
   * يتحقق من أن المستخدم مالك مكوّن
   */
  isOwner(componentId: string, userId: string, level?: OwnershipLevel): boolean {
    const comp = this.ownerships.get(componentId);
    if (!comp) return false;
    return comp.owners.some((o) => o.userId === userId && (!level || o.level === level));
  }

  /**
   * يُرجع جميع مكوّنات مستخدم معين
   */
  getOwnedBy(userId: string): ComponentOwnership[] {
    return [...this.ownerships.values()].filter((c) => c.owners.some((o) => o.userId === userId));
  }

  /**
   * يتحقق من الحاجة لـ Approval
   */
  requiresApproval(componentId: string, changeMaker: string): boolean {
    const comp = this.ownerships.get(componentId);
    if (!comp) return false;
    // إذا لم يكن المعدّل مالكاً → يحتاج Approval
    return !this.isOwner(componentId, changeMaker);
  }

  /**
   * يُولّد تقرير الملكية
   */
  generateReport(): OwnershipReport {
    const all = [...this.ownerships.values()];

    const orphaned = all.filter((c) => c.owners.length === 0);

    const ownerCounts = new Map<string, number>();
    for (const comp of all) {
      const primary = comp.primaryOwner;
      ownerCounts.set(primary.userId, (ownerCounts.get(primary.userId) ?? 0) + 1);
    }
    const overloaded = [...ownerCounts.entries()]
      .filter(([, count]) => count > 10)
      .map(([userId, componentCount]) => {
        const owner = all.find((c) => c.primaryOwner.userId === userId)!.primaryOwner;
        return { owner, componentCount };
      });

    const now = new Date();
    const overdueReviews = all.filter((c) => {
      if (!c.lastReviewed) return true;
      const daysAgo = (now.getTime() - c.lastReviewed.getTime()) / (1000 * 60 * 60 * 24);
      return daysAgo > c.reviewFrequencyDays;
    });

    const criticalWithSingleOwner = all.filter((c) => c.isCritical && c.owners.length < 2);

    return {
      totalComponents: all.length,
      orphanedComponents: orphaned,
      overloadedOwners: overloaded,
      overdueReviews,
      criticalWithSingleOwner,
      summary: `${all.length} components tracked. ${orphaned.length} orphaned, ${criticalWithSingleOwner.length} critical with single owner.`,
    };
  }

  /**
   * يُولّد CODEOWNERS file format
   */
  generateCodeOwners(): string {
    const lines = [
      "# CODEOWNERS — Auto-generated by Weaver Ownership Registry",
      "# Do not edit manually",
      "",
    ];

    for (const comp of this.ownerships.values()) {
      if (comp.path) {
        const owners = comp.owners.map((o) => `@${o.email.split("@")[0]}`).join(" ");
        lines.push(`${comp.path} ${owners}`);
      }
    }

    return lines.join("\n");
  }

  list(): ComponentOwnership[] {
    return [...this.ownerships.values()];
  }
}

export const ownershipRegistry = new OwnershipRegistry();
