/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedConnectorsRouteImport } from './routes/_authenticated/connectors'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedMonitorRouteImport } from './routes/_authenticated/monitor'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStatusRouteImport } from './routes/_authenticated/status'
import { Route as AuthenticatedTraceRouteImport } from './routes/_authenticated/trace'
import { Route as AuthenticatedWorkerRouteImport } from './routes/_authenticated/worker'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as SSplatRouteImport } from './routes/s/$'
import { Route as AuthenticatedCThreadIdRouteImport } from './routes/_authenticated/c.$threadId'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicLiveRouteImport } from './routes/api/public/live'
import { Route as ApiPublicExecutorActionRouteImport } from './routes/api/public/executor/$action'
import { Route as ApiPublicHooksMessageIntegrityRouteImport } from './routes/api/public/hooks/message-integrity'
import { Route as ApiPublicHooksSchedulerRouteImport } from './routes/api/public/hooks/scheduler'
import { Route as ApiPublicRtSplatRouteImport } from './routes/api/public/rt/$'
import { Route as ApiPublicSiteSplatRouteImport } from './routes/api/public/site/$'
import { Route as ApiPublicTgProjectIdRouteImport } from './routes/api/public/tg/$projectId'
import { Route as ApiPublicWorkerTickRouteImport } from './routes/api/public/worker/tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectorsRoute = AuthenticatedConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonitorRoute = AuthenticatedMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatusRoute = AuthenticatedStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTraceRoute = AuthenticatedTraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkerRoute = AuthenticatedWorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SSplatRoute = SSplatRouteImport.update({
  id: '/s/$',
  path: '/s/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCThreadIdRoute = AuthenticatedCThreadIdRouteImport.update({
  id: '/c/$threadId',
  path: '/c/$threadId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLiveRoute = ApiPublicLiveRouteImport.update({
  id: '/api/public/live',
  path: '/api/public/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExecutorActionRoute = ApiPublicExecutorActionRouteImport.update({
  id: '/api/public/executor/$action',
  path: '/api/public/executor/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksMessageIntegrityRoute =
  ApiPublicHooksMessageIntegrityRouteImport.update({
    id: '/api/public/hooks/message-integrity',
    path: '/api/public/hooks/message-integrity',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSchedulerRoute = ApiPublicHooksSchedulerRouteImport.update({
  id: '/api/public/hooks/scheduler',
  path: '/api/public/hooks/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRtSplatRoute = ApiPublicRtSplatRouteImport.update({
  id: '/api/public/rt/$',
  path: '/api/public/rt/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSiteSplatRoute = ApiPublicSiteSplatRouteImport.update({
  id: '/api/public/site/$',
  path: '/api/public/site/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTgProjectIdRoute = ApiPublicTgProjectIdRouteImport.update({
  id: '/api/public/tg/$projectId',
  path: '/api/public/tg/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerTickRoute = ApiPublicWorkerTickRouteImport.update({
  id: '/api/public/worker/tick',
  path: '/api/public/worker/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/connectors': typeof AuthenticatedConnectorsRoute
  '/health': typeof AuthenticatedHealthRoute
  '/monitor': typeof AuthenticatedMonitorRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/status': typeof AuthenticatedStatusRoute
  '/trace': typeof AuthenticatedTraceRoute
  '/worker': typeof AuthenticatedWorkerRoute
  '/api/chat': typeof ApiChatRoute
  '/s/$': typeof SSplatRoute
  '/c/$threadId': typeof AuthenticatedCThreadIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/live': typeof ApiPublicLiveRoute
  '/api/public/executor/$action': typeof ApiPublicExecutorActionRoute
  '/api/public/hooks/message-integrity': typeof ApiPublicHooksMessageIntegrityRoute
  '/api/public/hooks/scheduler': typeof ApiPublicHooksSchedulerRoute
  '/api/public/rt/$': typeof ApiPublicRtSplatRoute
  '/api/public/site/$': typeof ApiPublicSiteSplatRoute
  '/api/public/tg/$projectId': typeof ApiPublicTgProjectIdRoute
  '/api/public/worker/tick': typeof ApiPublicWorkerTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/connectors': typeof AuthenticatedConnectorsRoute
  '/health': typeof AuthenticatedHealthRoute
  '/monitor': typeof AuthenticatedMonitorRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/status': typeof AuthenticatedStatusRoute
  '/trace': typeof AuthenticatedTraceRoute
  '/worker': typeof AuthenticatedWorkerRoute
  '/api/chat': typeof ApiChatRoute
  '/s/$': typeof SSplatRoute
  '/c/$threadId': typeof AuthenticatedCThreadIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/live': typeof ApiPublicLiveRoute
  '/api/public/executor/$action': typeof ApiPublicExecutorActionRoute
  '/api/public/hooks/message-integrity': typeof ApiPublicHooksMessageIntegrityRoute
  '/api/public/hooks/scheduler': typeof ApiPublicHooksSchedulerRoute
  '/api/public/rt/$': typeof ApiPublicRtSplatRoute
  '/api/public/site/$': typeof ApiPublicSiteSplatRoute
  '/api/public/tg/$projectId': typeof ApiPublicTgProjectIdRoute
  '/api/public/worker/tick': typeof ApiPublicWorkerTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/connectors': typeof AuthenticatedConnectorsRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/monitor': typeof AuthenticatedMonitorRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/status': typeof AuthenticatedStatusRoute
  '/_authenticated/trace': typeof AuthenticatedTraceRoute
  '/_authenticated/worker': typeof AuthenticatedWorkerRoute
  '/api/chat': typeof ApiChatRoute
  '/s/$': typeof SSplatRoute
  '/_authenticated/c/$threadId': typeof AuthenticatedCThreadIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/live': typeof ApiPublicLiveRoute
  '/api/public/executor/$action': typeof ApiPublicExecutorActionRoute
  '/api/public/hooks/message-integrity': typeof ApiPublicHooksMessageIntegrityRoute
  '/api/public/hooks/scheduler': typeof ApiPublicHooksSchedulerRoute
  '/api/public/rt/$': typeof ApiPublicRtSplatRoute
  '/api/public/site/$': typeof ApiPublicSiteSplatRoute
  '/api/public/tg/$projectId': typeof ApiPublicTgProjectIdRoute
  '/api/public/worker/tick': typeof ApiPublicWorkerTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/connectors'
    | '/health'
    | '/monitor'
    | '/platform'
    | '/settings'
    | '/status'
    | '/trace'
    | '/worker'
    | '/api/chat'
    | '/s/$'
    | '/c/$threadId'
    | '/api/public/health'
    | '/api/public/live'
    | '/api/public/executor/$action'
    | '/api/public/hooks/message-integrity'
    | '/api/public/hooks/scheduler'
    | '/api/public/rt/$'
    | '/api/public/site/$'
    | '/api/public/tg/$projectId'
    | '/api/public/worker/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/connectors'
    | '/health'
    | '/monitor'
    | '/platform'
    | '/settings'
    | '/status'
    | '/trace'
    | '/worker'
    | '/api/chat'
    | '/s/$'
    | '/c/$threadId'
    | '/api/public/health'
    | '/api/public/live'
    | '/api/public/executor/$action'
    | '/api/public/hooks/message-integrity'
    | '/api/public/hooks/scheduler'
    | '/api/public/rt/$'
    | '/api/public/site/$'
    | '/api/public/tg/$projectId'
    | '/api/public/worker/tick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/connectors'
    | '/_authenticated/health'
    | '/_authenticated/monitor'
    | '/_authenticated/platform'
    | '/_authenticated/settings'
    | '/_authenticated/status'
    | '/_authenticated/trace'
    | '/_authenticated/worker'
    | '/api/chat'
    | '/s/$'
    | '/_authenticated/c/$threadId'
    | '/api/public/health'
    | '/api/public/live'
    | '/api/public/executor/$action'
    | '/api/public/hooks/message-integrity'
    | '/api/public/hooks/scheduler'
    | '/api/public/rt/$'
    | '/api/public/site/$'
    | '/api/public/tg/$projectId'
    | '/api/public/worker/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  SSplatRoute: typeof SSplatRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicLiveRoute: typeof ApiPublicLiveRoute
  ApiPublicExecutorActionRoute: typeof ApiPublicExecutorActionRoute
  ApiPublicHooksMessageIntegrityRoute: typeof ApiPublicHooksMessageIntegrityRoute
  ApiPublicHooksSchedulerRoute: typeof ApiPublicHooksSchedulerRoute
  ApiPublicRtSplatRoute: typeof ApiPublicRtSplatRoute
  ApiPublicSiteSplatRoute: typeof ApiPublicSiteSplatRoute
  ApiPublicTgProjectIdRoute: typeof ApiPublicTgProjectIdRoute
  ApiPublicWorkerTickRoute: typeof ApiPublicWorkerTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connectors': {
      id: '/_authenticated/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof AuthenticatedConnectorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitor': {
      id: '/_authenticated/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof AuthenticatedMonitorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/status': {
      id: '/_authenticated/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AuthenticatedStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trace': {
      id: '/_authenticated/trace'
      path: '/trace'
      fullPath: '/trace'
      preLoaderRoute: typeof AuthenticatedTraceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker': {
      id: '/_authenticated/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof AuthenticatedWorkerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$': {
      id: '/s/$'
      path: '/s/$'
      fullPath: '/s/$'
      preLoaderRoute: typeof SSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/c/$threadId': {
      id: '/_authenticated/c/$threadId'
      path: '/c/$threadId'
      fullPath: '/c/$threadId'
      preLoaderRoute: typeof AuthenticatedCThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live': {
      id: '/api/public/live'
      path: '/api/public/live'
      fullPath: '/api/public/live'
      preLoaderRoute: typeof ApiPublicLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/executor/$action': {
      id: '/api/public/executor/$action'
      path: '/api/public/executor/$action'
      fullPath: '/api/public/executor/$action'
      preLoaderRoute: typeof ApiPublicExecutorActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/message-integrity': {
      id: '/api/public/hooks/message-integrity'
      path: '/api/public/hooks/message-integrity'
      fullPath: '/api/public/hooks/message-integrity'
      preLoaderRoute: typeof ApiPublicHooksMessageIntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scheduler': {
      id: '/api/public/hooks/scheduler'
      path: '/api/public/hooks/scheduler'
      fullPath: '/api/public/hooks/scheduler'
      preLoaderRoute: typeof ApiPublicHooksSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rt/$': {
      id: '/api/public/rt/$'
      path: '/api/public/rt/$'
      fullPath: '/api/public/rt/$'
      preLoaderRoute: typeof ApiPublicRtSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site/$': {
      id: '/api/public/site/$'
      path: '/api/public/site/$'
      fullPath: '/api/public/site/$'
      preLoaderRoute: typeof ApiPublicSiteSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tg/$projectId': {
      id: '/api/public/tg/$projectId'
      path: '/api/public/tg/$projectId'
      fullPath: '/api/public/tg/$projectId'
      preLoaderRoute: typeof ApiPublicTgProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/tick': {
      id: '/api/public/worker/tick'
      path: '/api/public/worker/tick'
      fullPath: '/api/public/worker/tick'
      preLoaderRoute: typeof ApiPublicWorkerTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedConnectorsRoute: typeof AuthenticatedConnectorsRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedMonitorRoute: typeof AuthenticatedMonitorRoute
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatusRoute: typeof AuthenticatedStatusRoute
  AuthenticatedTraceRoute: typeof AuthenticatedTraceRoute
  AuthenticatedWorkerRoute: typeof AuthenticatedWorkerRoute
  AuthenticatedCThreadIdRoute: typeof AuthenticatedCThreadIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedConnectorsRoute: AuthenticatedConnectorsRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedMonitorRoute: AuthenticatedMonitorRoute,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatusRoute: AuthenticatedStatusRoute,
  AuthenticatedTraceRoute: AuthenticatedTraceRoute,
  AuthenticatedWorkerRoute: AuthenticatedWorkerRoute,
  AuthenticatedCThreadIdRoute: AuthenticatedCThreadIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  SSplatRoute: SSplatRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicLiveRoute: ApiPublicLiveRoute,
  ApiPublicExecutorActionRoute: ApiPublicExecutorActionRoute,
  ApiPublicHooksMessageIntegrityRoute: ApiPublicHooksMessageIntegrityRoute,
  ApiPublicHooksSchedulerRoute: ApiPublicHooksSchedulerRoute,
  ApiPublicRtSplatRoute: ApiPublicRtSplatRoute,
  ApiPublicSiteSplatRoute: ApiPublicSiteSplatRoute,
  ApiPublicTgProjectIdRoute: ApiPublicTgProjectIdRoute,
  ApiPublicWorkerTickRoute: ApiPublicWorkerTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
